//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno_Materia
    {
        public int AlunoMateriaID { get; set; }
        public int AlunoID { get; set; }
        public int MateriaID { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual materia materia { get; set; }
    }
}
